const users = [
  {
    username: "test",
    password: "password",
    name: "Test User",
    avatar: null,
    about: "Test user for development purposes.",
  },
  {
    username: "hiker_john",
    password: "password",
    name: "John Doe",
    avatar: null,
    about: "Love hiking and outdoor adventures.",
  },
  {
    username: "bookworm_jane",
    password: "password",
    name: "Jane Smith",
    avatar: null,
    about: "Avid reader and coffee enthusiast.",
  },
  {
    username: "techie_alice",
    password: "password",
    name: "Alice Jones",
    avatar: null,
    about: "Tech geek and foodie.",
  },
  {
    username: "music_bob",
    password: "password",
    name: "Bob Brown",
    avatar: null,
    about: "Musician and artist.",
  },
  {
    username: "streamer_charlie",
    password: "password",
    name: "Charlie Clark",
    avatar: null,
    about: "Gamer and streamer.",
  },
  {
    username: "fit_david",
    password: "password",
    name: "David Wilson",
    avatar: null,
    about: "Fitness enthusiast.",
  },
  {
    username: "travel_emma",
    password: "password",
    name: "Emma Davis",
    avatar: null,
    about: "Travel blogger.",
  },
  {
    username: "history_frank",
    password: "password",
    name: "Frank Miller",
    avatar: null,
    about: "History buff.",
  },
  {
    username: "photo_grace",
    password: "password",
    name: "Grace Martin",
    avatar: null,
    about: "Photographer.",
  },
  {
    username: "chef_harry",
    password: "password",
    name: "Harry Thompson",
    avatar: null,
    about: "Chef and food critic.",
  },
  {
    username: "art_isabella",
    password: "password",
    name: "Isabella White",
    avatar: null,
    about: "Artist and illustrator.",
  },
  {
    username: "yoga_james",
    password: "password",
    name: "James Anderson",
    avatar: null,
    about: "Yoga instructor and wellness coach.",
  },
  {
    username: "science_kate",
    password: "password",
    name: "Kate Robinson",
    avatar: null,
    about: "Science enthusiast and researcher.",
  },
  {
    username: "diy_liam",
    password: "password",
    name: "Liam Harris",
    avatar: null,
    about: "DIY hobbyist and woodworker.",
  },
  {
    username: "fashion_mia",
    password: "password",
    name: "Mia Jackson",
    avatar: null,
    about: "Fashion designer and stylist.",
  },
  {
    username: "cyclist_noah",
    password: "password",
    name: "Noah Lewis",
    avatar: null,
    about: "Cycling enthusiast and triathlete.",
  },
  {
    username: "garden_olivia",
    password: "password",
    name: "Olivia Walker",
    avatar: null,
    about: "Gardener and plant lover.",
  },
  {
    username: "film_peter",
    password: "password",
    name: "Peter Hall",
    avatar: null,
    about: "Film critic and cinephile.",
  },
  {
    username: "chess_quinn",
    password: "password",
    name: "Quinn Allen",
    avatar: null,
    about: "Chess player and strategy game lover.",
  },
  {
    username: "surf_rachel",
    password: "password",
    name: "Rachel Young",
    avatar: null,
    about: "Surfer and beach lover.",
  },
];

export default users;
