const users = [
  {
    username: "test",
    password: "password",
    name: "Test User",
    avatar: null,
    about: "Test user for development purposes.",
  },
  {
    username: "hiker_john",
    password: "password",
    name: "John Doe",
    avatar: null,
    about: "Love hiking and outdoor adventures.",
  },
  {
    username: "bookworm_jane",
    password: "password",
    name: "Jane Smith",
    avatar: null,
    about: "Avid reader and coffee enthusiast.",
  },
  {
    username: "techie_alice",
    password: "password",
    name: "Alice Jones",
    avatar: null,
    about: "Tech geek and foodie.",
  },
  {
    username: "music_bob",
    password: "password",
    name: "Bob Brown",
    avatar: null,
    about: "Musician and artist.",
  },
  {
    username: "streamer_charlie",
    password: "password",
    name: "Charlie Clark",
    avatar: null,
    about: "Gamer and streamer.",
  },
  {
    username: "fit_david",
    password: "password",
    name: "David Wilson",
    avatar: null,
    about: "Fitness enthusiast.",
  },
  {
    username: "travel_emma",
    password: "password",
    name: "Emma Davis",
    avatar: null,
    about: "Travel blogger.",
  },
  {
    username: "history_frank",
    password: "password",
    name: "Frank Miller",
    avatar: null,
    about: "History buff.",
  },
  {
    username: "photo_grace",
    password: "password",
    name: "Grace Martin",
    avatar: null,
    about: "Photographer.",
  },
  {
    username: "chef_harry",
    password: "password",
    name: "Harry Thompson",
    avatar: null,
    about: "Chef and food critic.",
  },
];

export default users;
