name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  frontend:
    uses: ./.github/workflows/frontend.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    uses: ./.github/workflows/e2e.yml
    secrets:
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
      VITE_WS_URL: ${{ secrets.VITE_WS_URL }}

  deploy:
    needs: [backend, frontend, e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Trigger backend deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}
        run: curl ${{ secrets.RENDER_SERVICE_URL }}
      - name: Trigger frontend deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_SERVICE_URL }}
