name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  frontend:
    uses: ./.github/workflows/frontend.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deployment_pipeline:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
        env:
          CI: true
          PORT: ${{ secrets.PORT }}
          DATABASE_URL: postgres://postgres:mysecretpassword@localhost:5432/postgres
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [backend, frontend, deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Trigger backend deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}
        run: curl ${{ secrets.RENDER_SERVICE_URL }}
      - name: Trigger frontend deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_SERVICE_URL }}
